{
 "title": "PS2Alerts - Aggregator",
 "description": "Shows all metrics related to the Aggregator processing module",
 "tags": [
  "ps2alerts",
  "aggregator"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(aggregator_instances_gauge, environment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Alerts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(type) (aggregator_instances_gauge{environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregators online",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance) (up{job=\"ps2alerts_aggregator\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages by World",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(world) (increase(aggregator_zone_message_count{environment=\"$environment\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alert Status", "type": "alertlist", "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 } },
  { "title": "Event Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Event Type processing time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, eventType) (rate(aggregator_event_processing_histogram_bucket{environment=\"$environment\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful messages by type",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(type) (increase(aggregator_zone_message_count{result=\"successful\", environment=\"$environment\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Unmatched messages to instances",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "sum by(event_type) (increase(aggregator_queue_messages_count{environment=\"$environment\", type=\"instance_mismatch\"}[$__rate_interval]))",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Failed messages by type",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "sum by(type) (increase(aggregator_queue_messages_count{environment=\"$environment\", type=\"discard\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(type) (increase(aggregator_zone_message_count{environment=\"$environment\", result=\"timeout\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache misses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "increase(aggregator_cache_hitmiss_count{environment=\"$environment\", result=\"cache_miss\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Redis Key Length",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 43 },
   "targets": [
    {
     "expr": "aggregator_cache_keys_gauge{environment=\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker results",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by(broker, result) (rate(aggregator_broker_count{environment=\"$environment\", result!~\"census_item_found|census_item_missing|cache_hit|cache_miss\"}[$__rate_interval]))",
     "legendFormat": "{{broker}}: {{result}}"
    }
   ]
  },
  {
   "title": "Broker cache rates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 43 },
   "targets": [
    {
     "expr": "sum(increase(aggregator_broker_count{environment=\"$environment\", result=\"cache_hit\", broker=\"character\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(aggregator_broker_count{environment=\"$environment\", result=\"cache_miss\", broker=\"character\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    { "expression": "$A/($A+$B)*100", "type": "math" },
    {
     "expr": "sum(increase(aggregator_broker_count{environment=\"$environment\", result=\"cache_hit\", broker=\"item\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(aggregator_broker_count{environment=\"$environment\", result=\"cache_miss\", broker=\"item\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    { "expression": "$D/($D+$E)*100", "type": "math" },
    {
     "expr": "sum(increase(aggregator_broker_count{environment=\"$environment\", result=\"cache_hit\", broker=\"facility_data\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(aggregator_broker_count{environment=\"$environment\", result=\"cache_miss\", broker=\"facility_data\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    { "expression": "$F/($F+$G)*100", "type": "math" }
   ]
  },
  { "title": "External Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "External endpoint requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(endpoint, provider) (increase(aggregator_external_requests_count{environment=\"$environment\"}[$__rate_interval])) / 4",
     "legendFormat": "{{provider}}: {{endpoint}}"
    }
   ]
  },
  {
   "title": "External endpoint unsuccessful requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum by(result, provider) (increase(aggregator_external_requests_count{environment=\"$environment\", result=~\"error|retry|empty\"}[$__rate_interval])) / 4",
     "legendFormat": "{{provider}}: {{result}}"
    }
   ]
  },
  {
   "title": "Census endpoint volumes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (increase(aggregator_external_requests_count{environment=\"$environment\", provider=\"census\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Census endpoint roundtimes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, endpoint) (rate(aggregator_external_requests_histogram_bucket{environment=\"$environment\", provider=\"census\"}[$__rate_interval]))) / 4",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Census errors / retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "targets": [
    {
     "expr": "sum by(result) (increase(aggregator_external_requests_count{environment=\"$environment\", result=~\"error|retry\", provider=\"census\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PS2Alerts API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by(endpoint) (increase(aggregator_external_requests_count{provider=\"ps2alerts_api\"}[$__rate_interval])) / 4",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PS2Alerts API roundtimes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, endpoint) (rate(aggregator_external_requests_histogram_bucket{provider=\"ps2alerts_api\"}[$__rate_interval]))) / 4",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PS2Alerts API errors / retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "targets": [
    {
     "expr": "sum by(result) (increase(aggregator_external_requests_count{environment=\"$environment\", result=~\"error|retry\", provider=\"ps2alerts_api\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Watchlist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Unknown facilities / items",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "sum by(type) (aggregator_cache_keys_gauge{type=~\"unknown_facilities|unknown_items\"})",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}