---
- hosts: localhost
  vars:
    HOME: "{{ lookup('env', 'HOME') }}"
    USER: "{{ lookup('env', 'USER') }}"
    ca_path_debian: /usr/local/share/ca-certificates
    ca_path:
      RedHat:
        6: /usr/local/share/ca-certificates
        7: /etc/pki/ca-trust/source/anchors
      Debian:
        7: '{{ ca_path_debian }}'
        8: '{{ ca_path_debian }}'
        18: '{{ ca_path_debian }}'
        19: '{{ ca_path_debian }}'
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure bash aliases file exists
      copy:
        content: ""
        dest: "{{ HOME }}/.bash_aliases"
        force: no
        owner: "{{ USER }}"
        mode: 0660

    - name: Install bash aliases for standardised commands
      blockinfile:
        path: "{{ HOME }}/.bash_aliases"
        marker: "# {mark} PS2ALERTS ANSIBLE MANAGED BLOCK #"
        block: |
          ## Aggregator
          alias ps2alerts-aggregator="cd {{ aggregator_dir | realpath }}"
          alias ps2alerts-aggregator-init="ansible-playbook {{ aggregator_dir | realpath }}/provisioning/dev/init.yml"
          alias ps2alerts-aggregator-start="ansible-playbook {{ aggregator_dir | realpath }}/provisioning/dev/start.yml"
          alias ps2alerts-aggregator-stop="ansible-playbook {{ aggregator_dir | realpath }}/provisioning/dev/stop.yml"
          alias ps2alerts-aggregator-dev="ps2alerts-aggregator-stop && ps2alerts-aggregator-start && ps2alerts-aggregator-logs"
          alias ps2alerts-aggregator-msg="ansible-playbook {{ aggregator_dir | realpath }}/provisioning/admin-aggregator-publish.yml"
          alias ps2alerts-aggregator-term="docker exec -it ps2alerts-aggregator bash"
          alias ps2alerts-aggregator-logs="docker logs -f ps2alerts-aggregator"
          ## API
          alias ps2alerts-api="cd {{ api_dir | realpath }}"
          alias ps2alerts-api-init="ansible-playbook {{ api_dir | realpath }}/provisioning/dev/init.yml"
          alias ps2alerts-api-start="ansible-playbook {{ api_dir | realpath }}/provisioning/dev/start.yml"
          alias ps2alerts-api-stop="ansible-playbook {{ api_dir | realpath }}/provisioning/dev/stop.yml"
          alias ps2alerts-api-dev="ps2alerts-api-stop && ps2alerts-api-start && docker logs -f ps2alerts-api"
          alias ps2alerts-api-term="docker exec -it ps2alerts-api bash"
          alias ps2alerts-api-logs="docker logs -f ps2alerts-api"
          ## Website
          alias ps2alerts-website="cd {{ website_dir | realpath }}"
          alias ps2alerts-website-init="ansible-playbook {{ website_dir | realpath }}/provisioning/dev/init.yml"
          alias ps2alerts-website-start="ansible-playbook {{ website_dir | realpath }}/provisioning/dev/start.yml"
          alias ps2alerts-website-stop="ansible-playbook {{ website_dir | realpath }}/provisioning/dev/stop.yml"
          alias ps2alerts-website-dev="ps2alerts-website-stop && ps2alerts-website-start && ps2alerts-website-logs"
          alias ps2alerts-website-term="docker exec -it ps2alerts-website bash"
          ## Stack
          alias ps2alerts-stack="cd {{ stack_dir | realpath }}"
          alias ps2alerts-stack-start="ansible-playbook {{ stack_dir | realpath }}/start-dev.yml"
          alias ps2alerts-stack-stop="ansible-playbook {{ stack_dir | realpath }}/stop-dev.yml"
          ## Global Commands
          alias ps2alerts="cd {{ project_dir | realpath }}"
          alias ps2alerts-start="ps2alerts-stack-start && ps2alerts-api-init && ps2alerts-website-start && ps2alerts-aggregator-init"
          alias ps2alerts-stop="ps2alerts-aggregator-stop && ps2alerts-api-stop && ps2alerts-website-stop && ps2alerts-stack-stop"
          alias ps2alerts-logs-all="docker logs -f ps2alerts-api ps2alerts-website ps2alerts-aggregator"
          alias ps2alerts-reprovision="sudo ansible-playbook {{ stack_dir | realpath }}/init.yml"

    # - name: Install ca-certificates package on RHEL systems
    #   yum:
    #     name: ca-certificates
    #     state: present
    #   when: ansible_os_family == "RedHat"

    # - name: Install ca-certificates package on Debian systems
    #   apt:
    #     name: ca-certificates
    #     state: present
    #     update_cache: yes
    #   when: ansible_os_family == "Debian"

    - name: Import hosts into /etc/hosts
      blockinfile:
        path: /etc/hosts
        marker: "# {mark} PS2ALERTS ANSIBLE MANAGED BLOCK #"
        block: |
          127.0.0.1 dev.api.ps2alerts.com
          127.0.0.1 dev.router.ps2alerts.com
          127.0.0.1 dev.ps2alerts.com
      become: yes

    - name: "Create {{ data_dir }} dir"
      file:
        path: "{{ data_dir }}"
        state: directory

    ## WIP WIP WIP
    - name: Make certs dir
      file:
        path: "{{ certs_dir }}"
        state: directory

    # - name: Start mkcert container and generate the certs
    #   docker_container:
    #     name: ps2alerts-mkcert
    #     image: vishnunair/docker-mkcert
    #     state: started
    #     env:
    #       domain: "dev.ps2alerts.com,api.dev.ps2alerts.com,wss.dev.ps2alerts.com"
    #     volumes:
    #       - "{{ certs_dir }}:/root/.local/share/mkcert"
    #     labels:
    #       traefik.enable: "false"

    # - name: Wait for certs to be generated (grab a snickers)
    #   wait_for:
    #     path: "{{ cert_dir }}/{{ item }}"
    #     state: present
    #   with_items:
    #     - dev.ps2alerts.com.pem
    #     - api.dev.ps2alerts.com.pem
    #     - rootCA.pem

    # - name: Copy certificate authority to trusted ca path of the os
    #   copy:
    #     src: "{{ item }}"
    #     dest: "{{ ca_path[ansible_os_family][ansible_distribution_major_version|int] }}/"
    #     owner: root
    #     group: root
    #     mode: 0644
    #   with_fileglob:
    #     - "{{ certs_dir }}*"
    #   notify:
    #     - update trusted ca debian
    #     - update trusted ca redhat

    # - name: Stop mkcert
    #   docker_container:
    #     name: ps2alerts-mkcert
    #     state: stopped

    - debug:
        msg: "👉 Remember to source your '~/.bash_aliases' file or restart your terminal!"

  handlers:
    - name: update trusted ca debian
      shell: /usr/sbin/update-ca-certificates && echo "Certs updated!"
      when: ansible_os_family == "Debian"

    - name: update trusted ca redhat
      shell: /bin/update-ca-trust && echo "Certs updated!"
      when: ansible_os_family == "RedHat"
