---
- hosts: localhost
  vars:
    - USER: "{{ lookup('env', 'HOME') }}"
  vars_files:
    - vars.yml
  tasks:
    - name: Import hosts into /etc/hosts
      blockinfile:
        path: /etc/hosts
        marker: "# {mark} PS2ALERTS ANSIBLE MANAGED BLOCK #"
        block: |
          127.0.0.1 dev.api.ps2alerts.com
          127.0.0.1 dev.wss.ps2alerts.com
          127.0.0.1 dev.ps2alerts.com

    - name: Install bash aliases for standardised commands
      blockinfile:
        path: "{{ USER }}/.bash_aliases"
        marker: "# {mark} PS2ALERTS ANSIBLE MANAGED BLOCK #"
        block: |
          ## API
          alias ps2alerts-api-start="ansible-playbook {{ api_dir | realpath }}/provisioning/dev/start.yml"
          alias ps2alerts-api-stop="ansible-playbook {{ api_dir | realpath }}/provisioning/dev/stop.yml"
          alias ps2alerts-api-term="docker exec -it ps2alerts-api bash"
          ## Website
          alias ps2alerts-website-start="ansible-playbook {{ website_dir | realpath }}/provisioning/dev/start.yml"
          alias ps2alerts-website-stop="ansible-playbook {{ website_dir | realpath }}/provisioning/dev/stop.yml"
          alias ps2alerts-website-term="docker exec -it ps2alerts-website bash"
          ## Websocket
          alias ps2alerts-websocket-start="ansible-playbook {{ websocket_dir | realpath }}/provisioning/dev/start.yml"
          alias ps2alerts-websocket-stop="ansible-playbook {{ websocket_dir | realpath }}/provisioning/dev/stop.yml"
          alias ps2alerts-websocket-term="docker exec -it ps2alerts-websocket bash"
          ## Stack
          alias ps2alerts-stack-start="ansible-playbook {{ stack_dir | realpath }}/start-dev.yml"
          alias ps2alerts-stack-stop="ansible-playbook {{ stack_dir | realpath }}/stop-dev.yml"
          ## Global Commands
          alias ps2alerts="{{ project_dir }}"
          alias ps2alerts-start="ps2alerts-stack-start && ps2alerts-api-start && ps2alerts-website-start && ps2alerts-websocket-start"
          alias ps2alerts-stop="ps2alerts-stack-stop && ps2alerts-api-stop && ps2alerts-website-stop && ps2alerts-websocket-stop"

    - name: Create /data/ps2alerts dir
      file:
        path: /data/ps2alerts
        state: directory

    - debug:
        msg: "Remember to source your '.bash_aliases' file or restart your terminal!"