---
- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/vars.yml"
  tasks:
    - debug:
        msg: "========= 🚀 HOUSTON, WE ARE GO FOR LAUNCH 🚀 ========="

    - name: Install docker on localhost
      pip:
        name: docker
        state: present

    - name: Create docker network
      docker_network:
        name: ps2alerts
        state: present

    - name: Start Traefik Router
      docker_container:
        name: ps2alerts-router
        image: traefik:v2.2
        state: started
        recreate: yes
        volumes:
          - ./traefik/logs:/var/log/traefik
          - ./traefik/config:/config
          - ./traefik/traefik.yml:/etc/traefik/traefik.yml
          - /var/run/docker.sock:/var/run/docker.sock
          - "{{ certs_dir }}:/etc/certs"
        labels:
          traefik.enable: "true"
          traefik.backend: "traefik"
          traefik.port: "8080"
        ports:
          - 80:80
          - 443:443
          - 8080:8080
        networks:
          - name: "ps2alerts"

    - name: Start Database
      docker_container:
        name: ps2alerts-db
        image: mongo:4.2
        state: started
        volumes:
          - ./mongo/init/init-mongo.js:/docker-entrypoint-initdb.d/init-monjo.js
          - ./mongo/mongod.conf:/etc/mongod.conf
          - ./mongo:/data/mongo-host
          - "{{ db_dir }}:/data/db"
        env:
          MONGO_INITDB_DATABASE: ps2alerts
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: foobar
        ports:
          - 27017-27019:27017-27019
        networks:
          - name: "ps2alerts"
        labels:
          traefik.enable: "false"

    - name: Start Redis
      docker_container:
        name: ps2alerts-redis
        image: redis:6
        state: started
        volumes:
          - "{{ redis_dir }}:/data"
        ports:
          - 6379:6379
        networks:
          - name: "ps2alerts"
        labels:
          traefik.enable: "false"

    - name: Start RabbitMQ
      docker_container:
        name: ps2alerts-mq
        image: rabbitmq:3.8-management
        ports:
          - 4369:4369
          - 5672:5672
          - 15672:15672
          - 25672:25672
        volumes:
          - "{{ mq_dir }}:/var/lib/rabbitmq"
        networks:
          - name: "ps2alerts"
        labels:
          traefik.enable: "false"

    - name: Wait for Rabbit to be fully available...
      shell: curl --head --silent http://localhost:15672
      register: result
      until: result.stdout.find("200 OK") != -1
      retries: 20
      delay: 5

    - name: Create RabbitMQ Exchange
      rabbitmq_exchange:
        name: ps2alerts
        vhost: /
        login_user: guest
        login_password: "guest"
