---
- hosts: localhost

  vars_files:
    - "{{ playbook_dir }}/vars.yml"

  tasks:
    - debug:
        msg: "========= 🕸️ HOUSTON, WE ARE GO FOR LAUNCH 🕸️ ========="

    - name: Install docker on localhost
      pip:
        name: docker
        state: present

    - name: Create docker network
      docker_network:
        name: ps2alerts
        state: present

    - name: Start Traefik Router
      docker_container:
        name: ps2alerts-router
        image: traefik:v2.2
        state: started
        recreate: yes
        volumes:
          - ./traefik/logs:/var/log/traefik
          - ./traefik/config:/config
          - ./traefik/traefik.yml:/etc/traefik/traefik.yml
          - /var/run/docker.sock:/var/run/docker.sock
          - /data/ps2alerts/certs:/etc/certs
        labels:
          traefik.enable: "true"
          traefik.backend: "traefik"
          traefik.port: "8080"
        ports:
          - 80:80
          - 443:443
          - 8080:8080

    - name: Start Database
      docker_container:
        name: ps2alerts-db
        image: mariadb:10.3
        state: started
        volumes:
          - "{{ db_dir }}:/var/lib/mysql"
        env:
          MYSQL_ROOT_PASSWORD: foobar
        ports:
          - 3306:3306
        networks:
          - name: "ps2alerts"
        labels:
          traefik.enable: "false"

    - name: Start Redis
      docker_container:
        name: ps2alerts-redis
        image: redis:5
        state: started
        volumes:
          - "{{ redis_dir }}:/data"
        ports:
          - 6379:6379
        networks:
          - name: "ps2alerts"
        labels:
          traefik.enable: "false"