---
- hosts: localhost
  tasks:
    - name: Stop Traefik Router
      docker_container:
        name: ps2alerts-router
        state: stopped

    - name: Stop Database
      docker_container:
        name: ps2alerts-db
        state: stopped

    - name: Stop Redis
      docker_container:
        name: ps2alerts-redis
        state: stopped

    - name: Stop RabbitMQ
      docker_container:
        name: ps2alerts-mq
        state: stopped