---
image:
  tag: 6.2.7

architecture: standalone

networkPolicy:
  enabled: true
  allowExternal: true

serviceAccount:
  create: false

## Use password authentication
auth:
  password: "foo" # Overridden by Terraform

## Redis config file
## ref: https://redis.io/topics/config
##
commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""

redisPort: 6379

master:
  disableCommands:
    - FLUSHALL
  resources:
    requests:
      memory: 192Mi
      cpu: 10m
    limits:
      memory: 192Mi
      cpu: 50m

  persistence:
    ## Persist data to a persistent volume (Redis Master) - OVERRIDDEN IN TERRAFORM
    existingClaim: "foo"
    size: 1Gi

#metrics:
#  enabled: false

volumePermissions:
  enabled: true
