providers:
  docker: {}

accessLog:
  filePath: "/var/log/traefik/traefik-access.log"
  bufferingSize: 100

log:
  level: "DEBUG"

api:
  insecure: true

http:
  routers:
    api-router:
      rule: "Host('api.dev.ps2alerts.com')"
      entrypoints:
        - websecure
      tls:
        domains:
          - main: "api.dev.ps2alerts.com"

entryPoints:
  websecure:
    address: ":443"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 60
        graceTimeOut: 60
      respondingTimeouts:
        readTimeout: 60
        writeTimeout: 60
        idleTimeout: 60
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/api.dev.ps2alerts.com.pem
        keyFile: /etc/certs/api.dev.ps2alerts.com-key.pem
  certificates:
    - certFile: /etc/certs/api.dev.ps2alerts.com.pem
      keyFile: /etc/certs/api.dev.ps2alerts.com-key.pem
    - certFile: /etc/certs/dev.ps2alerts.com.pem
      keyFile: /etc/certs/dev.ps2alerts.com-key.pem
    - certFile: /etc/certs/wss.dev.ps2alerts.com.pem
      keyFile: /etc/certs/wss.dev.ps2alerts.com-key.pem

metrics:
  prometheus: true