providers:
  docker: {}

api:
  insecure: true

serversTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls: {}
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 60
        graceTimeOut: 60
      respondingTimeouts:
        readTimeout: 60
        writeTimeout: 60
        idleTimeout: 60
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
tls:
  options:
    default:
      minVersion: VersionTLS12
    mintls13:
      minVersion: VersionTLS13
    cipherSuites:
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  certificates:
    - certFile: /etc/certs/api.dev.ps2alerts.com.pem
      keyFile: /etc/certs/api.dev.ps2alerts.com-key.pem
    - certFile: /etc/certs/dev.ps2alerts.com.pem
      keyFile: /etc/certs/dev.ps2alerts.com-key.pem
    - certFile: /etc/certs/wss.dev.ps2alerts.com.pem
      keyFile: /etc/certs/wss.dev.ps2alerts.com-key.pem

metrics:
  prometheus: true