---
providers:
  docker:
    exposedByDefault: false

accessLog:
  filePath: "/var/log/traefik/traefik-access.log"
  bufferingSize: 100

log:
  level: "DEBUG"

api:
  insecure: true

entryPoints:
  web:
    address: ":80"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 30
        graceTimeOut: 30
      respondingTimeouts:
        readTimeout: 30
        writeTimeout: 30
        idleTimeout: 30
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
  websecure:
    address: ":443"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 30
        graceTimeOut: 30
      respondingTimeouts:
        readTimeout: 30
        writeTimeout: 30
        idleTimeout: 30
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
#tls:
#  stores:
#    default:
#      defaultCertificate:
#        certFile: /etc/certs/api.dev.ps2alerts.com.pem
#        keyFile: /etc/certs/api.dev.ps2alerts.com-key.pem
#  certificates:
#    - certFile: /etc/certs/api.dev.ps2alerts.com.pem
#      keyFile: /etc/certs/api.dev.ps2alerts.com-key.pem
#    - certFile: /etc/certs/dev.ps2alerts.com.pem
#      keyFile: /etc/certs/dev.ps2alerts.com-key.pem
#    - certFile: /etc/certs/wss.dev.ps2alerts.com.pem
#      keyFile: /etc/certs/wss.dev.ps2alerts.com-key.pem
