tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/api.dev.ps2alerts.com.pem
        keyFile: /etc/certs/api.dev.ps2alerts.com-key.pem
  certificates:
    - certFile: /etc/certs/api.dev.ps2alerts.com.pem
      keyFile: /etc/certs/api.dev.ps2alerts.com-key.pem
    - certFile: /etc/certs/dev.ps2alerts.com.pem
      keyFile: /etc/certs/dev.ps2alerts.com-key.pem
    - certFile: /etc/certs/wss.dev.ps2alerts.com.pem
      keyFile: /etc/certs/wss.dev.ps2alerts.com-key.pem
