services:
  website:
    container_name: website
    image: maelstromeous/ps2alerts:website-production-latest
    restart: unless-stopped
    ports:
      - "80:80"
  api-aggregator:
    container_name: api-aggregator
    image: maelstromeous/ps2alerts:api-production-latest
    depends_on:
      - db
      - rabbit
      - redis
    env_file:
      - api.env
      - rabbit.env
      - redis.env
    restart: unless-stopped
    environment:
      AGGREGATOR_ENABLED: "true"
      RABBITMQ_QUEUE: api-queue-production
      DB_POOL_SIZE: 50
    networks:
      - ps2alerts
  api-cron:
    container_name: api-cron
    image: maelstromeous/ps2alerts:api-production-latest
    restart: unless-stopped
    depends_on:
      - db
      - redis
    env_file:
      - api.env
      - redis.env
    environment:
      CRON_ENABLED: "true"
    networks:
      - ps2alerts
  api-rest:
    container_name: api-rest
    image: maelstromeous/ps2alerts:api-production-latest
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "81:3000"
    env_file:
      - api.env
      - redis.env
    environment:
      REST_ENABLED: "true"
    networks:
      - ps2alerts
  assets:
    container_name: assets
    image: maelstromeous/ps2alerts:assets-latest
    restart: unless-stopped
    env_file:
      - collector.env
    ports:
      - "82:80"
  collector-pc:
    container_name: collector-pc
    image: ghcr.io/nanite-systems/stream-collector:1.3.2
    restart: unless-stopped
    depends_on:
      - rabbit
    env_file:
      - collector.env
    environment:
      PS2_ENVIRONMENT: ps2
    networks:
      - ps2alerts
  collector-ps4eu:
    container_name: collector-ps4eu
    image: ghcr.io/nanite-systems/stream-collector:1.3.2
    restart: unless-stopped
    depends_on:
      - rabbit
    env_file:
      - collector.env
    environment:
      PS2_ENVIRONMENT: ps2ps4eu
    networks:
      - ps2alerts
  collector-ps4us:
    container_name: collector-ps4us
    image: ghcr.io/nanite-systems/stream-collector:1.3.2
    restart: unless-stopped
    depends_on:
      - rabbit
    env_file:
      - collector.env
    environment:
      PS2_ENVIRONMENT: ps2ps4us
    networks:
      - ps2alerts
  aggregator-pc:
    container_name: aggregator-pc
    image: maelstromeous/ps2alerts:aggregator-production-latest
    restart: unless-stopped
    depends_on:
      - rabbit
      - redis
    env_file:
      - aggregator.env
      - redis.env
    ports:
      - "1337:1337"
    environment:
      CENSUS_ENVIRONMENT: ps2
    networks:
      - ps2alerts
  aggregator-ps4eu:
    container_name: aggregator-ps4eu
    image: maelstromeous/ps2alerts:aggregator-production-latest
    restart: unless-stopped
    depends_on:
      - rabbit
      - redis
    env_file:
      - aggregator.env
      - redis.env
    ports:
      - "1338:1337"
    environment:
      APP_PORT: 1338
      CENSUS_ENVIRONMENT: ps2ps4eu
    networks:
      - ps2alerts
  aggregator-ps4us:
    container_name: aggregator-ps4us
    image: maelstromeous/ps2alerts:aggregator-production-latest
    restart: unless-stopped
    depends_on:
      - rabbit
      - redis
    env_file:
      - aggregator.env
      - redis.env
    ports:
      - "1339:1337"
    environment:
      APP_PORT: 1339
      CENSUS_ENVIRONMENT: ps2ps4us
    networks:
      - ps2alerts
  db:
    container_name: db
    image: bitnami/mongodb:5.0.14-debian-11-r13
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/db:/bitnami
    networks:
      - ps2alerts
  rabbit:
    container_name: rabbit
    image: bitnami/rabbitmq:3.10.13
    restart: unless-stopped
    env_file:
      - rabbit.env
    environment:
      RABBITMQ_ERL_COOKIE: "REDACTED"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./volumes/rabbitmq:/bitnami
    networks:
      - ps2alerts
  redis:
    container_name: redis
    image: bitnamilegacy/redis:6.2
    restart: unless-stopped
    env_file:
      - redis.env
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/bitnami/redis/data
    networks:
      - ps2alerts
  ps2alerts-prometheus:
    container_name: ps2alerts-prom
    image: prom/prometheus
    restart: unless-stopped
    user: "1001"
    ports:
      - "9090:9090"
    volumes:
      - ./files/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/prometheus:/prometheus
    networks:
      - ps2alerts
  ps2alerts-grafana:
    container_name: ps2alerts-grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "1001"
    ports:
      - "9091:3000"
    volumes:
      - ./files/grafana/provisioning:/etc/grafana/provisioning
      - ./files/grafana/lib:/var/lib/grafana_docker
      - ./volumes/grafana:/var/lib/grafana
    networks:
      - ps2alerts
networks:
  ps2alerts:
    external: false
